
bean1 = * h2o.jenkov.container.TestProduct();

bean2 = * h2o.jenkov.container.script.SomeFactoryProduct("test");

bean3 = bean1.setValue1("bean3Value");

bean4 = bean1.setIntValue("beanValue".length());

bean5 = bean1.setValue1(h2o.jenkov.container.TestProduct.FIELD_VALUE);



/* bean5 = * h2o.jenkov.NonExistingClass(); */





/*
bean10 = * h2o.jenkov.NonExistingClass();
    config{
            local1 = bean10.get();
            local2 = bean10.getOther();
            $bean.set($0);
    }
    start{
        thread = $bean10.getThread();
    }
    stop{
        $bean10.stop();
        $thread.interrupt();
    }
    dispose {
        $bean10.getConnection().close();
        $local1.close();
    }


bean20 = 1 h2o.jenkov.NonExisitingClass();
bean21 = T h2o.jenkov.NonExisitingClass();
bean22 = F h2o.jenkov.NonExisitingClass();
bean22 = S h2o.jenkov.NonExisitingClass();
bean22 = R h2o.jenkov.NonExisitingClass();

bean20 = 1 h2o.jenkov.NonExisitingClass();
bean21 = 1T h2o.jenkov.NonExisitingClass();
bean22 = 1F h2o.jenkov.NonExisitingClass();
bean22 = 1S h2o.jenkov.NonExisitingClass();
bean22 = 1R h2o.jenkov.NonExisitingClass();

bean22 = 5 h2o.jenkov.NonExisitingClass();
bean22 = 5,10 h2o.jenkov.NonExisitingClass();



*/



    